name: Deploy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Predeploy
      run: npm run predeploy
    
    - name: Deploy
      run: |
        git config --global user.name utkarsh-sanjivan
        git config --global user.email utkarsh.sannu@gmail.com
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        github_token: ${{ secrets.TOKEN_FOR_REPO_DEPLOY }}
        repository: 'utkarsh-sanjivan/lets-chat-web-app'